### ISSUE TITLE
there shouldn't be any mines around the first sweep

### ISSUE THREAD

**Issue by xfangfang** [Creckeryop/MSweep#1]

**Comment by Creckeryop** [comment]
So where i can get minesweeper documentation to get all right rules?

**Comment by xfangfang** [comment]
Sorry, I don't know much about it. Just for this situation, if there are mines near the first click, then the game is not 100% solvable.
Perhaps some layout of mines may also lead to the problem having to be solved by guessing. If the random layout can not be proved to be 100% solvable, then it may be necessary to verify with code whether it can be solved after each mine layout is generated
